@extends:
    '@parent'

form:
    fields:
        sectionone:
            type:                              section
            title:                             Open Course Hub
            underline:                         true

            fields:
              test:
                  type: display
                  size: large
                  label:
                  markdown: true
                  content: "Settings for your Open Course Hub can now be found in the **Theme** settings for **My Theme**."
